-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 20:02:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema readoo_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `readoo_db` ;

-- -----------------------------------------------------
-- Schema readoo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `readoo_db` DEFAULT CHARACTER SET utf8 ;
USE `readoo_db` ;

-- -----------------------------------------------------
-- Table `readoo_db`.`AppUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`AppUser` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`AppUser` (
  `userId` INT(10) NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(20) NOT NULL,
  `userSurname` VARCHAR(45) NOT NULL,
  `userNick` VARCHAR(20) NOT NULL,
  `pass` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `userAboutMe` VARCHAR(140) NULL DEFAULT NULL,
  `karma` INT(10) ZEROFILL NULL,
  `avatarUrl` VARCHAR(50) NULL DEFAULT NULL,
  `visible` BOOLEAN NOT NULL,
  PRIMARY KEY (`userId`)
  -- INDEX `indexName` (`userId` ASC) VISIBLE,
  )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `readoo_db`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`Genre` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`Genre` (
  `genreId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`genreId`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `readoo_db`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`Book` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`Book` (
  `bookId` INT(10) NOT NULL AUTO_INCREMENT,
  `bookTittle` VARCHAR(45) NOT NULL,
  `bookAuthor` VARCHAR(45) NULL,
  `bookDescription` VARCHAR(140) NULL DEFAULT NULL,
  `bookReview` VARCHAR(140) NULL DEFAULT NULL,
  `bookLikes` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `bookDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `bookCoverUrl` VARCHAR(50) NULL DEFAULT NULL,
  `userId` INT(10) NOT NULL,
  `genreId` INT(10) UNSIGNED NOT NULL,
  `visible` BOOLEAN NOT NULL,
  PRIMARY KEY (`bookId`),
  -- INDEX indexName (`genreId` ASC) VISIBLE,
  -- INDEX `indexName` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_book_genreId`
    FOREIGN KEY (`genreId`)
    REFERENCES `readoo_db`.`Genre` (`genreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `readoo_db`.`UserLikeBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`UserLikeBook` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`UserLikeBook` (
  `userId` INT(10) NOT NULL,
  `bookId` INT(10) NOT NULL,
  PRIMARY KEY (`userId`, `bookId`),
  CONSTRAINT `fk_user_like_book_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUserd` (`userId`)
    ON DELETE NO ACTION		-- Have a look
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like_book_bookId`
    FOREIGN KEY (`bookId`)
    REFERENCES `readoo_db`.`Book` (`bookId`)
    ON DELETE NO ACTION		-- Have a look
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readoo_db`.`UserCommentsBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`UserCommentsBook` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`UserCommentsBook` (
  `commentId` INT(20) NOT NULL AUTO_INCREMENT,
  `userId` INT(10) NOT NULL,
  `bookId` INT(10) NOT NULL,
  `commentDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `commentText` VARCHAR(140) NOT NULL,
  `commentFatherId` INT(20) NOT NULL,
  PRIMARY KEY (`commentId`),
  CONSTRAINT `fk_user_comments_book_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_comments_book_commentFatherId`
    FOREIGN KEY (`commentFatherId`)
    REFERENCES `readoo_db`.`UserCommentsBook` (`commentId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_comments_book_bookId`
    FOREIGN KEY (`bookId`)
    REFERENCES `readoo_db`.`Book` (`bookId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readoo_db`.`UserReportsBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`UserReportsBook` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`UserReportsBook` (
  `userId` INT(10) NOT NULL,
  `bookId` INT(10) NOT NULL,
  `reportText` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`userId`, `bookId`),
  CONSTRAINT `fk_user_reports_book_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_reports_book_bookId`
    FOREIGN KEY (`bookId`)
    REFERENCES `readoo_db`.`Book` (`bookId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `readoo_db`.`UserReportsComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`UserReportsComment` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`UserReportsComment` (
  `userId` INT(10) NOT NULL,
  `commentId` INT(20) NOT NULL,
  `reportText` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`userId`, `commentId`),
  CONSTRAINT `fk_user_reports_comment_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_reports_comment_commentId`
    FOREIGN KEY (`commentId`)
    REFERENCES `readoo_db`.`UserCommentsBook` (`commentId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `readoo_db` ;

-- -----------------------------------------------------
-- Table `readoo_db`.`LastUserBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`LastUserBook` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`LastUserBook` (
  `userId` INT(10) NOT NULL,
  `bookId` INT(10) NOT NULL,
  `lastUserBookDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`, `bookId`),
  CONSTRAINT `fk_last_user_book_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_last_user_book_bookId`
    FOREIGN KEY (`bookId`)
    REFERENCES `readoo_db`.`Book` (`bookId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `readoo_db`.`UserGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`UserGenre` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`UserGenre` (
  `userId` INT(10) NOT NULL,
  `genreId` INT(10) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`userId`, `genreId`),
  CONSTRAINT `fk_user_genre_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_genre_genreId`
    FOREIGN KEY (`genreId`)
    REFERENCES `readoo_db`.`Genre` (`genreId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `readoo_db`.`UserLikesBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`UserLikesBook` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`UserLikesBook` (
  `userId` INT(10) NOT NULL,
  `bookId` INT(10) NOT NULL,
  `likeBoolean` BOOLEAN,
  PRIMARY KEY (`userId`, `bookId`),
  CONSTRAINT `fk_user_likes_book_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_likes_book_bookId`
    FOREIGN KEY (`bookId`)
    REFERENCES `readoo_db`.`Book` (`bookId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `readoo_db`.`LoginRegister`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readoo_db`.`LoginRegister` ;

CREATE TABLE IF NOT EXISTS `readoo_db`.`LoginRegister` (
  `userId` INT(10) NOT NULL,
  `loginRegisterDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`, `loginRegisterDate`),
  CONSTRAINT `fk_login_register_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `readoo_db`.`AppUser` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
  
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
