export default [
    // English
    {
        'Readoo': 'Readoo',
        'language': 'Language : ',
        'english': 'English',
        'spanish': 'Spanish',
        'something.goes.wrong': 'SOMETHING GOES WRONG! Try reolading page',
        'unique.user': 'Nick or E-mail. REMEMBER: they are unique',
        'nick.user': 'Nick: REMEMBER: it is unique',
        'nick.user.exists': 'Nick: What a pitty, this Nick already exists',
        'email.user.exists': 'E-mail: What a pitty, this E-mail already exists',
        'your.pass': 'Type your password',
        'repeat.pass': 'Repeat your pass',
        'old.pass': 'You have to write the current pass before change it',
        'your.email': 'Type your E-mail',
        'isnot.email': 'Write a reliable E-mail',
        'your.name': 'Write your name',
        'your.surname': 'Write your surname',
        'register': 'Register new user',
        'login': 'Log In',
        'cancel.register': 'Cancel',
        'pass.arnt.same': 'Both pass must be equal',
        'close': 'Close',
        'estatus': 'Status : ',
        'exploring.books': 'I´m looking for something cool.',
        'refreshing.my.mind': 'There were some books I used to like it.',
        'chatting': 'I´m chatting with my neighbours',
        'who.am.i': 'Who am I?',
        'look.for.books': 'Explore books',
        'favourites': 'My favourites',
        'chats': 'My chats',
        'profile': 'Profile',
        'user.image.avatar': 'User presentation image',
        'add.portrait.image': 'Add image as portrait',
        'about.you': 'Write something to share about you. (MAX: {0})',
        'delete.profile': 'Delete your own profile!',
        'save': 'Save',
        'no.changes': '* No changes detected. No it is necessary save anything!'
    },
    // Spanish
    {
        'Readoo': 'Readoo',
        'language': 'Idioma : ',
        'english': 'Inglés',
        'spanish': 'Español',
        'something.goes.wrong': '¡Algo ha ido mal! Prueba a recargar la página',
        'unique.user': 'Nick o E-mail. RECUERDA: son únicos',
        'nick.user': 'Nick: RECUERDA: es único',
        'nick.user.exists': 'Nick: Que pena, alguien se te ha adelantado',
        'email.user.exists': 'E-mail: Oh oh... este E-mail ya ha sido registrado',
        'your.pass': 'Tu contraseña',
        'repeat.pass': 'Repite tu contaseña',
        'old.pass': 'Tienes que escribir tu contraseña actual si pretendes cambiarla.',
        'your.email': 'Escribe tu E-mail',
        'isnot.email': 'Escribe una dirección de correo creíble',
        'register': 'Registrate',
        'login': 'Entrar',
        'cancel.register': 'Cancelar registro',
        'pass.arnt.same': 'Las contraseñas no coenciden',
        'close': 'Close',
        'estatus': 'Estado : ',
        'exploring.books': 'Buscando algo interesante.',
        'refreshing.my.mind': 'Había algo que me gustaba por aquí.',
        'chatting': 'Solo chateando con mis vecinos',
        'who.am.i': '¿Quién soy?',
        'look.for.books': 'Explora libros',
        'favourites': 'Mis favoritos',
        'chats': 'Mis conversaciones',
        'profile': 'Perfil',
        'user.image.avatar': 'Imagen de presentación',
        'add.portrait.image': 'Añadir imagen como retrato',
        'about.you': 'Escribe algo sobre tí para darte a conocer. (MAX: {0})',
        'delete.profile': '¡Eliminar tu perfil!',
        'save': 'Guardar',
        'no.changes': '* No se han detectado cambios. No es necesario guardar.'
    }
]