module.exports = {
    QUERY_ERROR: -1,
    DB_CONNECTION_FAIL: -2,
    QUERY_ERROR_DUPLICATE_ENTRY: -3,
    MAX_COMMENTARIES: 25,
    TOKEN_TIME: '12h',
    LANGUAGE_ENGLISH: 1,
    LANGUAGE_SPANISH: 2,
}
