module.exports = {
    QUERY_ERROR: -1,
    DB_CONNECTION_FAIL: -2,
    QUERY_ERROR_DUPLICATE_ENTRY: -3,
    MAX_COMMENTARIES: 5, // MAX COMMENTARIES PER REQUEST. IMPORTANT TO CHANGE THIS NUMBER ALSO IN THE FRONT APP (NUM_OF_COMENTARIES).
    TOKEN_TIME: '12h',
    LANGUAGE_ENGLISH: 1,
    LANGUAGE_SPANISH: 2,
}
