export default [
    // English
    {
        'Readoo': 'Readoo',
        'language': 'Language : ',
        'english': 'English',
        'spanish': 'Spanish',
        'loading': 'Loading...',
        'something.goes.wrong': 'SOMETHING GOES WRONG! Try reolading page',
        'no.user.logged': 'No user logged yet. Please log in or register to have some fun!',
        'unique.user': 'Nick or E-mail. REMEMBER: they are unique',
        'nick.user': 'Nick: REMEMBER: it is unique',
        'nick.user.exists': 'Nick: What a pitty, this Nick already exists',
        'email.user.exists': 'E-mail: What a pitty, this E-mail already exists',
        'your.pass': 'Type your password',
        'repeat.pass': 'Repeat your pass',
        'old.pass': 'You have to write the current pass before change it',
        'your.email': 'Type your E-mail',
        'isnot.email': 'Write a reliable E-mail',
        'your.name': 'Write your name',
        'your.surname': 'Write your surname',
        'register': 'Register new user',
        'login': 'Log In',
        'log.out': 'Log out',
        'cancel.register': 'Cancel',
        'pass.arnt.same': 'Both pass must be equal',
        'close': 'Close',
        'estatus': 'Status : ',
        'exploring.books': 'I´m looking for something cool.',
        'refreshing.my.mind': 'There were some books I used to like it.',
        'chatting': 'I´m chatting with my neighbours',
        'who.am.i': 'Who am I?',
        'look.for.books': 'Explore books',
        'favourites': 'My favourites',
        'chats': 'My chats',
        'profile': 'Profile',
        'profile.preview': 'Readoo user',
        'page.one.of': 'Page: {0} of {1}',
        'my.favourites.0': 'My favourite books',
        'my.favourites.1': 'My shared books',
        'user.image.avatar': 'User presentation image',
        'add.portrait.image': 'Add image as portrait',
        'about.you': 'Write something to share about you. (MAX: {0})',
        'karma': 'Your karma',
        'what.is.karma': 'The karma o level of karma is the amount of likes of your publications. This means that when more karma you own, more popular you are in Readoo.',
        'delete.profile': 'Delete your own profile!',
        'save': 'Save',
        'no.changes': '* No changes detected. No it is necessary save anything!',
        'saved.successfully': 'Saved successfully',
        'my.genres': 'My preferred genres',
        'items.selected': '{0} items selected',
        'upload.my.book': 'Upload my book',
        'book.title': 'Book title',
        'book.author': 'Book author',
        'book.description': 'Brief description of the book, do not tell spoilers please! (MAX: {0})',
        'book.personal': 'Your personal opinion (MAX: {0})',
        'book.need.image' : 'You have to post an image for a better chance of being shared',
        'book.add.cover.image': 'Add a cover',
        'book.must.add.cover.image': 'You must add a cover before upload the book',
        'upload': 'Upload',
        'cancel': 'Cancel',
        'complete.field': 'Complete this field',
        'couldnt.get.image': 'Oh damn! It wasn´t possible show the cover',
        'what.book.about': 'What is the book about:',
        'what.book.opinion': 'What is the owner opinion:',
        'what.book.likes': '{0} people think the book is cool.',
        'what.book.by': 'By:',
        'write.commentary': 'Write here a great commentary about the book (MAX: {0})',
        'write.commentary.answer': 'You can write an answer here... (MAX: {0})',
        'click.containt': 'Click on one image to see its content...',
        'commentaries': 'Commentaries:',
        'no.commentaries.yet': 'No commentaries yet. Yours will be the first, just do it!',
        'hide.commentaries': 'Hide commentaries',
        'show.commentaries': 'Show commentaries',
        'hide.subcommentaries': 'Hide subcommentaries',
        'show.subcommentaries': 'Show subcommentaries',
        'search.more.commentaries': 'Search more commentaries',
        'search.more.subcommentaries': 'Search more answers',
        'number.of.answers': '{0} answers',
        'answer': 'Answer{0}',
        'nothing.to.see': 'Nothing to see here! Continue your exploration in other button.',
        'no.image.avaliable': 'No image avaliable.',
        'no.books.yet': 'Are you a hater or you just do not like anything?',
        // Genres
        'theater': 'Theater',
        'drama': 'Drama',
        // Errors
        'user.id.not.provided': 'User Id not provided, please reload and try again',
        'timeout.error': 'Timeout while loading the page. Check your net connection. If the problem still existing could be a problem with the application server :-/',
        'failed.save': 'Something went wrong. Please keep calm. Here is the number of hope: {0}.',
        'failed.save.last.book': 'Something went wrong while registering the last book readed',
        'no.user.exists': 'The user doesn´t exist.',
        'wrong.pass': 'Not a valid password. Try again Hackerman.',
        'no.token.provided': 'It seems the sesson has been expired. Please, refresh the application and log in to continue.',
        'no.pass.coincidence': 'The old password doesn´t coencide with the password in use.',
        'no.image.preview': 'Image preview not avaliable.',
        'image.not.found': 'Image not found',
        'image.exceds.limit': 'The image file is bigger than our limit of 5MB. Cut it!',
        'data.not.found': 'Some required data has not been provided',
        'please.reload': 'Some error has occurred, please try to reload the page. Sorry for the inconveniences!',
        'commentaries.load.error': 'An error ocurred while fetching commentaries, it might be a fail with the NET or the server...',
        'favourites.load.error': 'An error ocurred while fetching your favourite books, it might be a fail with the NET or the server...',
        'not.hire.jastel': 'Bad connection again. Do not play Fornite!',
    },
    // Spanish
    {
        'Readoo': 'Readoo',
        'language': 'Idioma : ',
        'english': 'Inglés',
        'spanish': 'Español',
        'loading': 'Cargando...',
        'something.goes.wrong': '¡Algo ha ido mal! Prueba a recargar la página',
        'no.user.logged': '¿No estás has entrado todavía? Entra o registrate para usar la aplicación.',
        'unique.user': 'Nick o E-mail. RECUERDA: son únicos',
        'nick.user': 'Nick: RECUERDA: es único',
        'nick.user.exists': 'Nick: Que pena, alguien se te ha adelantado',
        'email.user.exists': 'E-mail: Oh oh... este E-mail ya ha sido registrado',
        'your.pass': 'Tu contraseña',
        'repeat.pass': 'Repite tu contaseña',
        'old.pass': 'Tienes que escribir tu contraseña actual si pretendes cambiarla.',
        'your.email': 'Escribe tu E-mail',
        'isnot.email': 'Escribe una dirección de correo creíble',
        'register': 'Registrate',
        'login': 'Entrar',
        'log.out': 'Salir',
        'cancel.register': 'Cancelar registro',
        'pass.arnt.same': 'Las contraseñas no coenciden',
        'close': 'Cerrar',
        'estatus': 'Estado : ',
        'exploring.books': 'Buscando algo interesante.',
        'refreshing.my.mind': 'Había algo que me gustaba por aquí.',
        'chatting': 'Solo chateando con mis vecinos',
        'who.am.i': '¿Quién soy?',
        'look.for.books': 'Explora libros',
        'favourites': 'Mis favoritos',
        'chats': 'Mis conversaciones',
        'profile': 'Perfil',
        'profile.preview': 'Usuario de Readoo',
        'page.one.of': 'Página: {0} of {1}',
        'my.favourites.0': 'Mis libros favoritos',
        'my.favourites.1': 'Mis libros compartidos',
        'user.image.avatar': 'Imagen de presentación',
        'add.portrait.image': 'Añadir imagen como retrato',
        'about.you': 'Escribe algo sobre tí para darte a conocer. (MAX: {0})',
        'karma': 'Tu karma',
        'what.is.karma': 'El karma o nivel de Karma es el número de likes totales que tienen tus pubicaciones, cuanto más karma significa que eres más popular en Readoo.',
        'delete.profile': '¡Eliminar tu perfil!',
        'save': 'Guardar',
        'no.changes': '* No se han detectado cambios. No es necesario guardar.',
        'saved.successfully': 'Se han guardado los datos correctamente',
        'my.genres': 'Mis generos preferidos',
        'items.selected': '{0} elementos seleccionados',
        'upload.my.book': 'Subir mi libro',
        'book.title': 'Título del libro',
        'book.author': 'Autor del libro',
        'book.description': 'Descripcion breve del libro, ¡no lo digas TODO! (MAX: {0})',
        'book.personal': 'Escribe tu opinión personal (MAX: {0})',
        'book.need.image' : 'Necesitas subir una imagen para tener más posibilidades de que te encuentren',
        'book.add.cover.image': 'Añade una portada',
        'book.must.add.cover.image': 'Debes añadir una portada para subirlo',
        'upload': 'Súbelo',
        'cancel': 'Cancelar',
        'complete.field': 'Completa este campo',
        'couldnt.get.image': 'Oh oh! No se ha cargado la imagen. Que mal!',
        'what.book.about': 'De qué va el libro:',
        'what.book.opinion': 'Cuál es la opinión de su dueño:',
        'what.book.likes': 'A {0} personas les mola el libro.',
        'what.book.by': 'De:',
        'write.commentary': 'Escribe aquí un buen comentario (MAX: {0})',
        'write.commentary.answer': '¿Quires compartir tu punto de vista? (MAX: {0})',
        'click.containt': 'Haz click en una imagen para ver su contenido...',
        'commentaries': 'Comentarios:',
        'no.commentaries.yet': 'No hay comentarios todavía. ¡Sé el primero en escribir!',
        'hide.commentaries': 'Ocultar comentarios',
        'show.commentaries': 'Mostrar comentarios',
        'hide.subcommentaries': 'Ocultar subcomentarios',
        'show.subcommentaries': 'Mostrar subcomentarios',
        'search.more.commentaries': 'Buscar más comentarios',
        'search.more.subcommentaries': 'Buscar más respuestas',
        'number.of.answers': '{0} respuestas',
        'answer': 'Respuesta{0}',
        'nothing.to.see': 'Aquí no hay nada que ver! Continua tu exploración en otra parte.',
        'no.image.avaliable': 'No hay ninguna imagen.',
        'no.books.yet': '¿Que pasa, no te gusta leer o es que simplemente aun no has empezado?',
        // Genres
        'theater': 'Teatro',
        'drama': 'Drama',
        // Errores
        'user.id.not.provided': 'Falta el ID de Usuario. Por favor, recarga el módulo y vuelve a intentarlo.',
        'timeout.error': 'Exceso de tiempo durante la carga. Comprueba tu conexión a la red. Si el problema persiste puede ser un fallo del servidor :-/',
        'failed.save': 'Oh oh... Algo no ha funcionado. Mantén la calma, aquí tienes el número de la esperanza: {0}',
        'failed.save.last.book': 'Algo a fallado en el registro del último libro leído.',
        'no.user.exists': 'El usuario informado no existe.',
        'wrong.pass': 'Contraseña no valida. Prueba otra vez Hackerman.',
        'no.token.provided': 'La sesión parece haber expirado. Por favor, refresca la pagina y vuelve a entrar para continuar.',
        'no.pass.coincidence': 'La contraseña antigüa no coencide con la contraseña ahora en uso.',
        'no.image.preview': 'Previsualización de imagen no disponible.',
        'image.not.found': 'Imagen no disponible',
        'image.exceds.limit': 'La imagen supera nuestro limite de 5MB. Recortala!',
        'data.not.found': 'Falta algún dato requerido',
        'please.reload': 'Ha ocurrido un error, prueba a recargar la página. ¡Disculpa las molestias!',
        'commentaries.load.error': 'Error en la carga de comentaries, puede ser un problema de red o fallo del servidor...',
        'favourites.load.error': 'Error en la carga de tus libros favoritos, puede ser un problema de red o fallo del servidor...',
        'not.hire.jastel': 'No contrates Jastel!'
    }
]